services:
  api_producer:
    container_name: api_producer
    build: .
    networks:
      - api_microservice
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

networks:
  api_microservice:
    external: true
    name: api_microservice